cfp/urls.py
from django.conf.urls import url

from . import views

app_name = 'cfp'
urlpatterns = [
    # add a home page here, change from index view
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'all-calls-for-proposals/$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<slug>[\w-]+)/$',
        views.CfPDetailView.as_view(), name='cfp_detail'),
    url(r'^(?P<pk>[0-9]+)/edit-cfp/$', views.edit_cfp, name='edit_cfp'),
]

cfp/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.urls import reverse
from autoslug import AutoSlugField


class Donor(models.Model):
    name = models.CharField(max_length=200, unique=True)
    abbrev = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.abbrev

    class Meta:
        ordering = ('name',)


class Theme(models.Model):
    theme = models.CharField(unique=True, max_length=50)

    def __str__(self):
        return self.theme

    class Meta:
        ordering = ('theme',)


class Zone(models.Model):
    zone = models.CharField(unique=True, max_length=200)

    def __str__(self):
        return self.zone

    class Meta:
        ordering = ('zone',)


class Cfp(models.Model):
    CURRENCY = (
        ('USD', 'US Dollars'),
        ('GBP', 'British Pound'),
        ('EUR', 'Euros'),
        ('KES', 'Kenya Shillings'),
        ('JPY', 'Japanese Yen'),
        ('CAD', 'Canadian Dollars'),
    )
    entered_at = models.DateTimeField(auto_now_add=True, editable=False)
    donor = models.ForeignKey(Donor, on_delete=models.CASCADE)
    title = models.CharField(
        max_length=200, unique=True, verbose_name='Call for proposals title')
    slug = AutoSlugField(max_length=255, null=True, editable=True, unique=True, populate_from='title')
    link = models.URLField(verbose_name='Call for proposals website')
    pub_date = models.DateField(verbose_name='Published')
    closing_date_provided = models.BooleanField(
        verbose_name='Closing date specified?')
    closing_date = models.DateField(
        null=True, blank=True, verbose_name='Closing date for applications')
    themes = models.ManyToManyField(Theme)
    zones = models.ManyToManyField(Zone)
    type_of_projects = models.TextField()
    # eligibility = models.TextField(verbose_name='Eligibility Criteria')
    funding_currency = models.CharField(max_length=3, choices=CURRENCY)
    grant_size_specified = models.BooleanField(
        verbose_name='Has the grant size been specified?')
    overall_budget_specified = models.BooleanField(
        verbose_name='Has the overall budget been specified?')
    overall_budget = models.FloatField(
        null=True, blank=True, verbose_name='Total or overall budget available')
    minimum_budget = models.FloatField(
        null=True, blank=True, verbose_name='Minimum budget for a project')
    maximum_budget = models.FloatField(
        null=True, blank=True, verbose_name='Maximum budget for a project')
    duration_specified = models.BooleanField(
        verbose_name='Project duration specified?')
    duration = models.PositiveIntegerField(
        null=True, blank=True, verbose_name='Maximum duration(in months) for a project')
    # how_to_apply = models.TextField()
    apply_here = models.URLField(blank=True)
    notes = models.TextField(blank=True)

    def get_absolute_url(self):
        return reverse('cfp:cfp_detail', args=[str(self.slug)])

    def __str__(self):
        return self.title

    def past_deadline(self):
        leo = datetime.date.today()
        deadline = self.closing_date
        return leo > deadline

    def no_closing_date(self):
        return self.closing_date is None

    cfp = models.Manager()

cfp/forms.py
from django import forms
from .models import Cfp


# class EditCfPForm(forms.Form):
#     cfp_title = forms.CharField(
# max_length=200, help_text='Enter the call for proposals title, 200
# characters max')

#     def clean_cfp_title(self):
#         data = self.cleaned_data['cfp_title']

#         return data

class EditCfPForm(forms.ModelForm):
    class Meta:
        model = Cfp
        fields = ['donor', 'title']




    # donor = models.ForeignKey(Donor, on_delete=models.CASCADE)
    # cfp_title = models.CharField(
    #     max_length=200, unique=True, verbose_name='Call for proposals title')
    # cfp_link = models.URLField(verbose_name='Call for proposals website')
    # pub_date = models.DateField(verbose_name='Published')
    # closing_date_provided = models.BooleanField(
    #     verbose_name='Closing date specified?')
    # closing_date = models.DateField(
    #     null=True, blank=True, verbose_name='Closing date for applications')
    # themes = models.ManyToManyField(Theme)
    # zones = models.ManyToManyField(Zone)
    # type_of_projects = models.TextField()
    # # eligibility = models.TextField(verbose_name='Eligibility Criteria')
    # funding_currency = models.CharField(max_length=3, choices=CURRENCY)
    # grant_size_specified = models.BooleanField(
    #     verbose_name='Has the grant size been specified?')
    # overall_budget_specified = models.BooleanField(
    #     verbose_name='Has the overall budget been specified?')
    # overall_budget = models.FloatField(
    #     null=True, blank=True, verbose_name='Total or overall budget available')
    # minimum_budget = models.FloatField(
    #     null=True, blank=True, verbose_name='Minimum budget for a project')
    # maximum_budget = models.FloatField(
    #     null=True, blank=True, verbose_name='Maximum budget for a project')
    # duration_specified = models.BooleanField(
    #     verbose_name='Project duration specified?')
    # duration = models.PositiveIntegerField(
    #     null=True, blank=True, verbose_name='Maximum duration(in months) for a project')
    # # how_to_apply = models.TextField()
    # apply_here = models.URLField(blank=True)
    # notes = models.TextField(blank=True)

cfp/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.views import generic
from django.shortcuts import render, get_object_or_404, redirect

from .models import Cfp, Donor, Theme, Zone
from .forms import EditCfPForm


def cfp_home(request):
    return render(request, 'cfp/cfp_home.html')


class IndexView(generic.ListView):
    template_name = 'cfp/index.html'
    context_object_name = 'all_cfps_list'

    def get_queryset(self):
        return Cfp.cfp.order_by('closing_date')


class CfPDetailView(generic.DetailView):
    model = Cfp
    template_name = 'cfp/cfp_detail.html'


# def edit_cfp(request, pk):
#     cfp_inst = get_object_or_404(Cfp, pk=pk)

#     # If this is a POST request then process the Form data
#     if request.method == 'POST':
#         # Create a form instance and populate it with data from the request
#         # (binding):
#         form = EditCfPForm(request.POST)

#         # Check if the form is valid
#         if form.is_valid():
#             cfp_inst = form.cleaned_data['cfp_title']
#             cfp_inst.save()

#             # redirect to a new URL:
#             return HttpResponseRedirect('/thank-you/')

#     else:
#         form = EditCfPForm(initial={'cfp_title': Cfp.cfp_title})
#     return render(request, 'cfp/edit_cfp.html', {'form': form})
def edit_cfp(request, pk):
    cfp = get_object_or_404(Cfp, pk=pk)
    # form = EditCfPForm(instance=cfp)

    if request.method == "POST":
        form = EditCfPForm(request.POST, instance=cfp)
        if form.is_valid():
            cfp = form.save(commit=False)
            cfp.save()
            return redirect('/')
    else:
        form = EditCfPForm(instance=cfp)
    return render(request, 'cfp/edit_cfp.html', {'form': form})

cfp/templates/cfp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <!-- Template Source - https://getbootstrap.com/docs/4.0/examples/dashboard/ -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">


    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #8DC63F;">
        <a class="navbar-brand" href="{% url 'cfp:index' %}">Health Poverty Action - Call for Proposals</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'cfp:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <!--
          <li class="nav-item">
            <a class="nav-link" href="#">Settings</a>
        </li>
        -->
                <!-- <li class="nav-item">
            <a class="nav-link" href="#">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Help</a>
        </li> -->
            </ul>
            <form class="form-inline mt-2 mt-md-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>



    <div class="container-fluid">
        <div class="row">
            <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar" style="background-color: #F78E1E;">
                <ul class="nav nav-pills flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'cfp:index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cfp:index' %}">Call for Proposals List</a>
                    </li>

                </ul>




            </nav>
            <main class="col-sm-9 ml-sm-auto col-md-10 pt-3" role="main">

                {% block content %}{% endblock %}

                <hr>

                <footer class="footer">
                    <div class="container">
                        <span class="text-muted">&copy; Health Poverty Action 2017. <a href="https://github.com/jgathogo" target="_blank">Credits</a></span>

                        <p class="text-muted">Powered by <a href="https://www.djangoproject.com/" target="_blank">Django</a></p>
                        <!--<span class="text-muted">Place sticky footer content here.</span>-->
                    </div>
                </footer>
            </main>
        </div>
    </div>






    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    <script src="{% static 'js/custom.js' %}"></script>



</body>

</html>

cfp/templates/cfp/cfp_detail.html
{% extends "cfp/base.html" %}
{% load humanize %}
{% block title %}Call for Proposal Detail{% endblock %}
{% block content %}

<h2>{{ cfp.cfp_title }}</h2>
<h4 style="color: red">Closing date for applications: {{ cfp.closing_date }}</h4>


<table class="table table-bordered">
<tbody>
    <tr>
        <th scope="row">Donor</th>
        <td>{{ cfp.donor.name }}</td>
    </tr>

    <tr>
        <th scope="row">Call for proposals website</th>
        <td><a href="{{ cfp.link }}">{{ cfp.link }}</a></td>
    </tr>

    <tr>
        <th scope="row">Publication date</th>
        <td>{{ cfp.pub_date }}</td>
    </tr>

    <tr>
        <th scope="row">Theme(s)</th>
        <td>

        {% for theme in cfp.themes.all %}

        {{ theme }},
         {% endfor %}
         </td>
    </tr>

    <tr>
        <th scope="row">Eligible location(zone)</th>
        <td>
        {% for zone in cfp.zones.all %}
        {{ zone }},
        {% endfor %}
        </td>
    </tr>

     <tr>
        <th scope="row">Type of projects</th>
        <td>{{ cfp.type_of_projects }}</td>
    </tr>

     <tr>
        <th scope="row">Total budget available</th>
        <td>{{ cfp.funding_currency }} {{ cfp.overall_budget|intcomma }}</td>
    </tr>

    <tr>
        <th scope="row">Minimum budget allowed for a project</th>
        <td>{{ cfp.funding_currency }} {{ cfp.minimum_budget|intcomma }}</td>
    </tr>

    <tr>
        <th scope="row">Maximum budget allowed for a project</th>
        <td>{{ cfp.funding_currency }} {{ cfp.maximum_budget|intcomma }}</td>
    </tr>

    <tr>
        <th scope="row">Maximum project duration(in months)</th>
        <td>{{ cfp.duration }}</td>
    </tr>

     <tr>
        <th scope="row">Notes</th>
        <td>{{ cfp.notes }}</td>
    </tr>

</tbody>

</table>

{% endblock %}

cfp/templates/cfp/cfp_home.html
{% extends "cfp/base.html" %}
{% block title %}Call for Proposals Home{% endblock %}
{% block content %}
    <h2>This is a H2 Heading</h2>
    <p>This is some paragraph</p>
{% endblock %}

cfp/templates/cfp/edit_cfp.html
{% extends "cfp/base.html" %}
{% load humanize %}
{% block title %}Edit Call for Proposal{% endblock %}
{% block content %}

<form action="" method="post" novalidate>

    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit" class="save btn btn-default">Save</button>

</form>



{% endblock %}

cfp/templates/cfp/index.html
{% extends "cfp/base.html" %}
{% load humanize %}
{% block title %}List of all Call for Proposals{% endblock %}
{% block content %}
    {% if all_cfps_list %}

<div class="table-responsive">
    <table class="table table-striped">
    <thead>
  <tr>
    <th>Donor</th>
    <th>Call for Proposals<br></th>
    <th>Theme</th>
    <th>Zone</th>
    <th>Funding</th>
    <th>Deadline for Submission<br></th>
  </tr>
  </thead>
  {% for cfp in all_cfps_list %}
  {% if not cfp.past_deadline or cfp.no_closing_date %}
  <tr>
    <td>{{ cfp.donor.name }}</td>
    <td><a href="{% url 'cfp:cfp_detail' cfp.slug %}">{{ cfp.title }}</a></td>
    <td>
        {% for theme in cfp.themes.all %}
        {{ theme }},
        {% endfor %}

    </td>

    <td>
    	{% for zone in cfp.zones.all %}
    	{{ zone }},
    	{% endfor %}


    <td>{{ cfp.funding_currency }} {{ cfp.maximum_budget|intcomma }}</td>
    <td>{{ cfp.closing_date }}</td>
  </tr>
  {% endif %}
   {% endfor %}
</table>
</div>




{% else %}
    <p>No Call for Proposals are available.</p>
{% endif %}
{% endblock %}